name: Build TWRP
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Cleanup Space
      run: |
        sudo apt-get purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell mysql* php* android*
        sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo apt-get autoremove -y
        sudo apt-get clean

    - name: Install Build Tools
      run: |
        sudo apt-get update
        sudo apt-get install -y gperf gcc-multilib gcc-10-multilib g++-multilib g++-10-multilib libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip bc bison build-essential curl flex g++-multilib gcc-multilib git gnupg gperf image-magick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev python3 python2

    - name: Install Repo Tool
      run: |
        mkdir ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        sudo ln -sf ~/bin/repo /usr/bin/repo

    - name: Initialize & Sync TWRP Source
      run: |
        mkdir twrp
        cd twrp
        git config --global user.name "rdbckp"
        git config --global user.email "rdbckp@github.com"
        repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-11
        repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags

    - name: Clone Device Tree
      run: |
        cd twrp
        git clone https://github.com/rdbckp/twrp_kernel_tree -b main device/samsung/a02

    - name: Build Recovery Image
      run: |
        cd twrp
        source build/envsetup.sh
        export ALLOW_MISSING_DEPENDENCIES=true
        lunch twrp_a02-eng
        make recoveryimage -j$(nproc --all)

    - name: Upload Recovery to Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: TWRP-A02-SM-A022F
        path: twrp/out/target/product/a02/recovery.img
        if-no-files-found: error

    - name: Create Release
      uses: softprops/action-gh-release@v2
      if: github.event_name == 'workflow_dispatch'
      with:
        files: twrp/out/target/product/a02/recovery.img
        name: TWRP Build SM-A022F
        tag_name: build-${{ github.run_number }}
        body: "Build otomatis TWRP A02 menggunakan Ubuntu Latest dan GitHub Actions v4."
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
